# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_normalizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text_normalizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15text_normalizer.proto\x12\x0ftext_normalizer\"R\n\x10NormalizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x30\n\x04mode\x18\x02 \x01(\x0e\x32\".text_normalizer.NormalizationMode\"\xaa\x01\n\x11NormalizeResponse\x12\x15\n\roriginal_text\x18\x01 \x01(\t\x12\x17\n\x0fnormalized_text\x18\x02 \x01(\t\x12\x1f\n\x17transformations_applied\x18\x03 \x03(\t\x12\x30\n\x04mode\x18\x04 \x01(\x0e\x32\".text_normalizer.NormalizationMode\x12\x12\n\nmodel_used\x18\x05 \x01(\t\"\x14\n\x12HealthCheckRequest\"e\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x14\n\x0cllm_provider\x18\x03 \x01(\t\x12\x11\n\tllm_model\x18\x04 \x01(\t*\'\n\x11NormalizationMode\x12\t\n\x05\x42\x41SIC\x10\x00\x12\x07\n\x03LLM\x10\x01\x32\xc5\x01\n\x15TextNormalizerService\x12R\n\tNormalize\x12!.text_normalizer.NormalizeRequest\x1a\".text_normalizer.NormalizeResponse\x12X\n\x0bHealthCheck\x12#.text_normalizer.HealthCheckRequest\x1a$.text_normalizer.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_normalizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALIZATIONMODE']._serialized_start=424
  _globals['_NORMALIZATIONMODE']._serialized_end=463
  _globals['_NORMALIZEREQUEST']._serialized_start=42
  _globals['_NORMALIZEREQUEST']._serialized_end=124
  _globals['_NORMALIZERESPONSE']._serialized_start=127
  _globals['_NORMALIZERESPONSE']._serialized_end=297
  _globals['_HEALTHCHECKREQUEST']._serialized_start=299
  _globals['_HEALTHCHECKREQUEST']._serialized_end=319
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=321
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=422
  _globals['_TEXTNORMALIZERSERVICE']._serialized_start=466
  _globals['_TEXTNORMALIZERSERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
