# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from text_normalizer.server.proto import text_normalizer_pb2 as text__normalizer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in text_normalizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextNormalizerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Normalize = channel.unary_unary(
                '/text_normalizer.TextNormalizerService/Normalize',
                request_serializer=text__normalizer__pb2.NormalizeRequest.SerializeToString,
                response_deserializer=text__normalizer__pb2.NormalizeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/text_normalizer.TextNormalizerService/HealthCheck',
                request_serializer=text__normalizer__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=text__normalizer__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TextNormalizerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Normalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextNormalizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Normalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Normalize,
                    request_deserializer=text__normalizer__pb2.NormalizeRequest.FromString,
                    response_serializer=text__normalizer__pb2.NormalizeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=text__normalizer__pb2.HealthCheckRequest.FromString,
                    response_serializer=text__normalizer__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'text_normalizer.TextNormalizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('text_normalizer.TextNormalizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextNormalizerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Normalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/text_normalizer.TextNormalizerService/Normalize',
            text__normalizer__pb2.NormalizeRequest.SerializeToString,
            text__normalizer__pb2.NormalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/text_normalizer.TextNormalizerService/HealthCheck',
            text__normalizer__pb2.HealthCheckRequest.SerializeToString,
            text__normalizer__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
