# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from concept_extractor.server.proto import concept_extractor_pb2 as concept__extractor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in concept_extractor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConceptExtractorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MatchConcepts = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/MatchConcepts',
                request_serializer=concept__extractor__pb2.MatchConceptsRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.MatchConceptsResponse.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/GetChildren',
                request_serializer=concept__extractor__pb2.GetChildrenRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.HierarchyResponse.FromString,
                _registered_method=True)
        self.GetDescendants = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/GetDescendants',
                request_serializer=concept__extractor__pb2.GetDescendantsRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.HierarchyResponse.FromString,
                _registered_method=True)
        self.GetAncestors = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/GetAncestors',
                request_serializer=concept__extractor__pb2.GetAncestorsRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.AncestorsResponse.FromString,
                _registered_method=True)
        self.GetRelationships = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/GetRelationships',
                request_serializer=concept__extractor__pb2.GetRelationshipsRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.RelationshipsResponse.FromString,
                _registered_method=True)
        self.GetValidAttributes = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/GetValidAttributes',
                request_serializer=concept__extractor__pb2.GetValidAttributesRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.AttributesResponse.FromString,
                _registered_method=True)
        self.GetAttributeRange = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/GetAttributeRange',
                request_serializer=concept__extractor__pb2.GetAttributeRangeRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.AttributeRangeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/concept_extractor.ConceptExtractorService/HealthCheck',
                request_serializer=concept__extractor__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=concept__extractor__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ConceptExtractorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MatchConcepts(self, request, context):
        """Match clinical text to SNOMED CT concepts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Get direct children of a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDescendants(self, request, context):
        """Get descendants of a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAncestors(self, request, context):
        """Get ancestors of a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelationships(self, request, context):
        """Get relationships for a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidAttributes(self, request, context):
        """Get valid MRCM attributes for a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeRange(self, request, context):
        """Get valid range values for an attribute
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConceptExtractorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MatchConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchConcepts,
                    request_deserializer=concept__extractor__pb2.MatchConceptsRequest.FromString,
                    response_serializer=concept__extractor__pb2.MatchConceptsResponse.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=concept__extractor__pb2.GetChildrenRequest.FromString,
                    response_serializer=concept__extractor__pb2.HierarchyResponse.SerializeToString,
            ),
            'GetDescendants': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescendants,
                    request_deserializer=concept__extractor__pb2.GetDescendantsRequest.FromString,
                    response_serializer=concept__extractor__pb2.HierarchyResponse.SerializeToString,
            ),
            'GetAncestors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAncestors,
                    request_deserializer=concept__extractor__pb2.GetAncestorsRequest.FromString,
                    response_serializer=concept__extractor__pb2.AncestorsResponse.SerializeToString,
            ),
            'GetRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelationships,
                    request_deserializer=concept__extractor__pb2.GetRelationshipsRequest.FromString,
                    response_serializer=concept__extractor__pb2.RelationshipsResponse.SerializeToString,
            ),
            'GetValidAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidAttributes,
                    request_deserializer=concept__extractor__pb2.GetValidAttributesRequest.FromString,
                    response_serializer=concept__extractor__pb2.AttributesResponse.SerializeToString,
            ),
            'GetAttributeRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeRange,
                    request_deserializer=concept__extractor__pb2.GetAttributeRangeRequest.FromString,
                    response_serializer=concept__extractor__pb2.AttributeRangeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=concept__extractor__pb2.HealthCheckRequest.FromString,
                    response_serializer=concept__extractor__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'concept_extractor.ConceptExtractorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('concept_extractor.ConceptExtractorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConceptExtractorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MatchConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/MatchConcepts',
            concept__extractor__pb2.MatchConceptsRequest.SerializeToString,
            concept__extractor__pb2.MatchConceptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/GetChildren',
            concept__extractor__pb2.GetChildrenRequest.SerializeToString,
            concept__extractor__pb2.HierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDescendants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/GetDescendants',
            concept__extractor__pb2.GetDescendantsRequest.SerializeToString,
            concept__extractor__pb2.HierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAncestors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/GetAncestors',
            concept__extractor__pb2.GetAncestorsRequest.SerializeToString,
            concept__extractor__pb2.AncestorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/GetRelationships',
            concept__extractor__pb2.GetRelationshipsRequest.SerializeToString,
            concept__extractor__pb2.RelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/GetValidAttributes',
            concept__extractor__pb2.GetValidAttributesRequest.SerializeToString,
            concept__extractor__pb2.AttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttributeRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/GetAttributeRange',
            concept__extractor__pb2.GetAttributeRangeRequest.SerializeToString,
            concept__extractor__pb2.AttributeRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/concept_extractor.ConceptExtractorService/HealthCheck',
            concept__extractor__pb2.HealthCheckRequest.SerializeToString,
            concept__extractor__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
