# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import snomed_pb2 as snomed__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in snomed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConceptServiceStub(object):
    """Service definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConcept = channel.unary_unary(
                '/snomed.ConceptService/GetConcept',
                request_serializer=snomed__pb2.GetConceptRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetConceptResponse.FromString,
                _registered_method=True)
        self.GetParents = channel.unary_unary(
                '/snomed.ConceptService/GetParents',
                request_serializer=snomed__pb2.GetParentsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetParentsResponse.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/snomed.ConceptService/GetChildren',
                request_serializer=snomed__pb2.GetChildrenRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetChildrenResponse.FromString,
                _registered_method=True)
        self.IsDescendantOf = channel.unary_unary(
                '/snomed.ConceptService/IsDescendantOf',
                request_serializer=snomed__pb2.IsDescendantOfRequest.SerializeToString,
                response_deserializer=snomed__pb2.IsDescendantOfResponse.FromString,
                _registered_method=True)
        self.GetConceptsBatch = channel.unary_unary(
                '/snomed.ConceptService/GetConceptsBatch',
                request_serializer=snomed__pb2.GetConceptsBatchRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetConceptsBatchResponse.FromString,
                _registered_method=True)
        self.GetRelationships = channel.unary_unary(
                '/snomed.ConceptService/GetRelationships',
                request_serializer=snomed__pb2.GetRelationshipsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetRelationshipsResponse.FromString,
                _registered_method=True)
        self.GetConcreteRelationships = channel.unary_unary(
                '/snomed.ConceptService/GetConcreteRelationships',
                request_serializer=snomed__pb2.GetConcreteRelationshipsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetConcreteRelationshipsResponse.FromString,
                _registered_method=True)
        self.GetOwlExpressions = channel.unary_unary(
                '/snomed.ConceptService/GetOwlExpressions',
                request_serializer=snomed__pb2.GetOwlExpressionsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetOwlExpressionsResponse.FromString,
                _registered_method=True)
        self.GetPreferredTerm = channel.unary_unary(
                '/snomed.ConceptService/GetPreferredTerm',
                request_serializer=snomed__pb2.GetPreferredTermRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetPreferredTermResponse.FromString,
                _registered_method=True)
        self.GetAssociations = channel.unary_unary(
                '/snomed.ConceptService/GetAssociations',
                request_serializer=snomed__pb2.GetAssociationsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetAssociationsResponse.FromString,
                _registered_method=True)
        self.GetReplacementConcept = channel.unary_unary(
                '/snomed.ConceptService/GetReplacementConcept',
                request_serializer=snomed__pb2.GetReplacementConceptRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetReplacementConceptResponse.FromString,
                _registered_method=True)


class ConceptServiceServicer(object):
    """Service definitions
    """

    def GetConcept(self, request, context):
        """Get a concept by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParents(self, request, context):
        """Get parent concepts (via IS_A relationships)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Get child concepts (reverse IS_A)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsDescendantOf(self, request, context):
        """Check if concept is descendant of another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConceptsBatch(self, request, context):
        """Get multiple concepts in a single request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelationships(self, request, context):
        """Get relationships for a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConcreteRelationships(self, request, context):
        """Get concrete relationships (with literal values)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOwlExpressions(self, request, context):
        """Get OWL expressions for a concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreferredTerm(self, request, context):
        """Get preferred term for a specific language
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssociations(self, request, context):
        """Get associations (historical relationships)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplacementConcept(self, request, context):
        """Get replacement concept for an inactive concept
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConceptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConcept,
                    request_deserializer=snomed__pb2.GetConceptRequest.FromString,
                    response_serializer=snomed__pb2.GetConceptResponse.SerializeToString,
            ),
            'GetParents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParents,
                    request_deserializer=snomed__pb2.GetParentsRequest.FromString,
                    response_serializer=snomed__pb2.GetParentsResponse.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=snomed__pb2.GetChildrenRequest.FromString,
                    response_serializer=snomed__pb2.GetChildrenResponse.SerializeToString,
            ),
            'IsDescendantOf': grpc.unary_unary_rpc_method_handler(
                    servicer.IsDescendantOf,
                    request_deserializer=snomed__pb2.IsDescendantOfRequest.FromString,
                    response_serializer=snomed__pb2.IsDescendantOfResponse.SerializeToString,
            ),
            'GetConceptsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConceptsBatch,
                    request_deserializer=snomed__pb2.GetConceptsBatchRequest.FromString,
                    response_serializer=snomed__pb2.GetConceptsBatchResponse.SerializeToString,
            ),
            'GetRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelationships,
                    request_deserializer=snomed__pb2.GetRelationshipsRequest.FromString,
                    response_serializer=snomed__pb2.GetRelationshipsResponse.SerializeToString,
            ),
            'GetConcreteRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConcreteRelationships,
                    request_deserializer=snomed__pb2.GetConcreteRelationshipsRequest.FromString,
                    response_serializer=snomed__pb2.GetConcreteRelationshipsResponse.SerializeToString,
            ),
            'GetOwlExpressions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOwlExpressions,
                    request_deserializer=snomed__pb2.GetOwlExpressionsRequest.FromString,
                    response_serializer=snomed__pb2.GetOwlExpressionsResponse.SerializeToString,
            ),
            'GetPreferredTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreferredTerm,
                    request_deserializer=snomed__pb2.GetPreferredTermRequest.FromString,
                    response_serializer=snomed__pb2.GetPreferredTermResponse.SerializeToString,
            ),
            'GetAssociations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssociations,
                    request_deserializer=snomed__pb2.GetAssociationsRequest.FromString,
                    response_serializer=snomed__pb2.GetAssociationsResponse.SerializeToString,
            ),
            'GetReplacementConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplacementConcept,
                    request_deserializer=snomed__pb2.GetReplacementConceptRequest.FromString,
                    response_serializer=snomed__pb2.GetReplacementConceptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snomed.ConceptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snomed.ConceptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConceptService(object):
    """Service definitions
    """

    @staticmethod
    def GetConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetConcept',
            snomed__pb2.GetConceptRequest.SerializeToString,
            snomed__pb2.GetConceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetParents',
            snomed__pb2.GetParentsRequest.SerializeToString,
            snomed__pb2.GetParentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetChildren',
            snomed__pb2.GetChildrenRequest.SerializeToString,
            snomed__pb2.GetChildrenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsDescendantOf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/IsDescendantOf',
            snomed__pb2.IsDescendantOfRequest.SerializeToString,
            snomed__pb2.IsDescendantOfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConceptsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetConceptsBatch',
            snomed__pb2.GetConceptsBatchRequest.SerializeToString,
            snomed__pb2.GetConceptsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetRelationships',
            snomed__pb2.GetRelationshipsRequest.SerializeToString,
            snomed__pb2.GetRelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConcreteRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetConcreteRelationships',
            snomed__pb2.GetConcreteRelationshipsRequest.SerializeToString,
            snomed__pb2.GetConcreteRelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOwlExpressions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetOwlExpressions',
            snomed__pb2.GetOwlExpressionsRequest.SerializeToString,
            snomed__pb2.GetOwlExpressionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreferredTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetPreferredTerm',
            snomed__pb2.GetPreferredTermRequest.SerializeToString,
            snomed__pb2.GetPreferredTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssociations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetAssociations',
            snomed__pb2.GetAssociationsRequest.SerializeToString,
            snomed__pb2.GetAssociationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplacementConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.ConceptService/GetReplacementConcept',
            snomed__pb2.GetReplacementConceptRequest.SerializeToString,
            snomed__pb2.GetReplacementConceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/snomed.SearchService/Search',
                request_serializer=snomed__pb2.SearchRequest.SerializeToString,
                response_deserializer=snomed__pb2.SearchResponse.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Search concepts by term
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=snomed__pb2.SearchRequest.FromString,
                    response_serializer=snomed__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snomed.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snomed.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.SearchService/Search',
            snomed__pb2.SearchRequest.SerializeToString,
            snomed__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RefsetServiceStub(object):
    """Reference set query service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRefsetMembers = channel.unary_unary(
                '/snomed.RefsetService/GetRefsetMembers',
                request_serializer=snomed__pb2.GetRefsetMembersRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetRefsetMembersResponse.FromString,
                _registered_method=True)
        self.GetRefsetsForConcept = channel.unary_unary(
                '/snomed.RefsetService/GetRefsetsForConcept',
                request_serializer=snomed__pb2.GetRefsetsForConceptRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetRefsetsForConceptResponse.FromString,
                _registered_method=True)


class RefsetServiceServicer(object):
    """Reference set query service
    """

    def GetRefsetMembers(self, request, context):
        """Get members of a reference set
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRefsetsForConcept(self, request, context):
        """Get all reference sets containing a concept (reverse lookup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefsetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRefsetMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRefsetMembers,
                    request_deserializer=snomed__pb2.GetRefsetMembersRequest.FromString,
                    response_serializer=snomed__pb2.GetRefsetMembersResponse.SerializeToString,
            ),
            'GetRefsetsForConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRefsetsForConcept,
                    request_deserializer=snomed__pb2.GetRefsetsForConceptRequest.FromString,
                    response_serializer=snomed__pb2.GetRefsetsForConceptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snomed.RefsetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snomed.RefsetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefsetService(object):
    """Reference set query service
    """

    @staticmethod
    def GetRefsetMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.RefsetService/GetRefsetMembers',
            snomed__pb2.GetRefsetMembersRequest.SerializeToString,
            snomed__pb2.GetRefsetMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRefsetsForConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.RefsetService/GetRefsetsForConcept',
            snomed__pb2.GetRefsetsForConceptRequest.SerializeToString,
            snomed__pb2.GetRefsetsForConceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EclServiceStub(object):
    """ECL query execution service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteEcl = channel.unary_unary(
                '/snomed.EclService/ExecuteEcl',
                request_serializer=snomed__pb2.ExecuteEclRequest.SerializeToString,
                response_deserializer=snomed__pb2.ExecuteEclResponse.FromString,
                _registered_method=True)
        self.MatchesEcl = channel.unary_unary(
                '/snomed.EclService/MatchesEcl',
                request_serializer=snomed__pb2.MatchesEclRequest.SerializeToString,
                response_deserializer=snomed__pb2.MatchesEclResponse.FromString,
                _registered_method=True)
        self.ExplainEcl = channel.unary_unary(
                '/snomed.EclService/ExplainEcl',
                request_serializer=snomed__pb2.ExplainEclRequest.SerializeToString,
                response_deserializer=snomed__pb2.ExplainEclResponse.FromString,
                _registered_method=True)
        self.IsSubsumedBy = channel.unary_unary(
                '/snomed.EclService/IsSubsumedBy',
                request_serializer=snomed__pb2.IsSubsumedByRequest.SerializeToString,
                response_deserializer=snomed__pb2.IsSubsumedByResponse.FromString,
                _registered_method=True)
        self.GetDescendants = channel.unary_unary(
                '/snomed.EclService/GetDescendants',
                request_serializer=snomed__pb2.GetDescendantsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetDescendantsResponse.FromString,
                _registered_method=True)
        self.GetAncestors = channel.unary_unary(
                '/snomed.EclService/GetAncestors',
                request_serializer=snomed__pb2.GetAncestorsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetAncestorsResponse.FromString,
                _registered_method=True)
        self.GetDirectParents = channel.unary_unary(
                '/snomed.EclService/GetDirectParents',
                request_serializer=snomed__pb2.GetDirectParentsRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetDirectParentsResponse.FromString,
                _registered_method=True)
        self.GetDirectChildren = channel.unary_unary(
                '/snomed.EclService/GetDirectChildren',
                request_serializer=snomed__pb2.GetDirectChildrenRequest.SerializeToString,
                response_deserializer=snomed__pb2.GetDirectChildrenResponse.FromString,
                _registered_method=True)


class EclServiceServicer(object):
    """ECL query execution service
    """

    def ExecuteEcl(self, request, context):
        """Execute an ECL expression and return matching concepts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchesEcl(self, request, context):
        """Check if a concept matches an ECL expression
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainEcl(self, request, context):
        """Explain the query plan for an ECL expression (debugging/optimization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsSubsumedBy(self, request, context):
        """Check if a concept is subsumed by another (direct subsumption test)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDescendants(self, request, context):
        """Get all descendants of a concept (optimized traversal)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAncestors(self, request, context):
        """Get all ancestors of a concept (optimized traversal)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDirectParents(self, request, context):
        """Get direct parents (one level, via IS_A)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDirectChildren(self, request, context):
        """Get direct children (one level, reverse IS_A)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EclServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteEcl': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteEcl,
                    request_deserializer=snomed__pb2.ExecuteEclRequest.FromString,
                    response_serializer=snomed__pb2.ExecuteEclResponse.SerializeToString,
            ),
            'MatchesEcl': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchesEcl,
                    request_deserializer=snomed__pb2.MatchesEclRequest.FromString,
                    response_serializer=snomed__pb2.MatchesEclResponse.SerializeToString,
            ),
            'ExplainEcl': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainEcl,
                    request_deserializer=snomed__pb2.ExplainEclRequest.FromString,
                    response_serializer=snomed__pb2.ExplainEclResponse.SerializeToString,
            ),
            'IsSubsumedBy': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSubsumedBy,
                    request_deserializer=snomed__pb2.IsSubsumedByRequest.FromString,
                    response_serializer=snomed__pb2.IsSubsumedByResponse.SerializeToString,
            ),
            'GetDescendants': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescendants,
                    request_deserializer=snomed__pb2.GetDescendantsRequest.FromString,
                    response_serializer=snomed__pb2.GetDescendantsResponse.SerializeToString,
            ),
            'GetAncestors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAncestors,
                    request_deserializer=snomed__pb2.GetAncestorsRequest.FromString,
                    response_serializer=snomed__pb2.GetAncestorsResponse.SerializeToString,
            ),
            'GetDirectParents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDirectParents,
                    request_deserializer=snomed__pb2.GetDirectParentsRequest.FromString,
                    response_serializer=snomed__pb2.GetDirectParentsResponse.SerializeToString,
            ),
            'GetDirectChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDirectChildren,
                    request_deserializer=snomed__pb2.GetDirectChildrenRequest.FromString,
                    response_serializer=snomed__pb2.GetDirectChildrenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snomed.EclService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snomed.EclService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EclService(object):
    """ECL query execution service
    """

    @staticmethod
    def ExecuteEcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/ExecuteEcl',
            snomed__pb2.ExecuteEclRequest.SerializeToString,
            snomed__pb2.ExecuteEclResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchesEcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/MatchesEcl',
            snomed__pb2.MatchesEclRequest.SerializeToString,
            snomed__pb2.MatchesEclResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainEcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/ExplainEcl',
            snomed__pb2.ExplainEclRequest.SerializeToString,
            snomed__pb2.ExplainEclResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsSubsumedBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/IsSubsumedBy',
            snomed__pb2.IsSubsumedByRequest.SerializeToString,
            snomed__pb2.IsSubsumedByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDescendants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/GetDescendants',
            snomed__pb2.GetDescendantsRequest.SerializeToString,
            snomed__pb2.GetDescendantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAncestors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/GetAncestors',
            snomed__pb2.GetAncestorsRequest.SerializeToString,
            snomed__pb2.GetAncestorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDirectParents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/GetDirectParents',
            snomed__pb2.GetDirectParentsRequest.SerializeToString,
            snomed__pb2.GetDirectParentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDirectChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snomed.EclService/GetDirectChildren',
            snomed__pb2.GetDirectChildrenRequest.SerializeToString,
            snomed__pb2.GetDirectChildrenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
