"""Pydantic models for REST API request/response."""

from coding_orchestrator.models.requests import (
    AnswerQuestionRequest,
    CodeOptions,
    CodeRequest,
    CodeWithQuestionsRequest,
    ConceptSearchRequest,
    CreateSessionRequest,
    EclMatchRequest,
    EclRequest,
    ExtractRequest,
    GenerateQuestionsRequest,
    NormalizeRequest,
    SubsumptionRequest,
)
from coding_orchestrator.models.responses import (
    AbbreviationResponse,
    AnsweredQuestionResponse,
    AnswerResponse,
    AttributeResponse,
    AttributeValueResponse,
    ClinicalPhraseResponse,
    CodeResponse,
    CodeWithQuestionsResponse,
    ConceptMatchResponse,
    ConceptResponse,
    ConceptResultResponse,
    ConceptWithQuestionsResponse,
    EclMatchResponse,
    EclResponse,
    ErrorResponse,
    ExtractResponse,
    GenerateQuestionsResponse,
    HealthResponse,
    HierarchyResponse,
    ModifierResponse,
    NormalizeResponse,
    QuestionOptionResponse,
    QuestionResponse,
    RelationshipResponse,
    SessionResponse,
    SubsumptionResponse,
)

__all__ = [
    # Requests
    "CodeRequest",
    "CodeOptions",
    "NormalizeRequest",
    "ExtractRequest",
    "EclRequest",
    "EclMatchRequest",
    "SubsumptionRequest",
    "ConceptSearchRequest",
    # Phase 4 Requests
    "CodeWithQuestionsRequest",
    "CreateSessionRequest",
    "AnswerQuestionRequest",
    "GenerateQuestionsRequest",
    # Responses
    "CodeResponse",
    "NormalizeResponse",
    "ExtractResponse",
    "ConceptResultResponse",
    "ConceptMatchResponse",
    "ConceptResponse",
    "EclResponse",
    "EclMatchResponse",
    "SubsumptionResponse",
    "HierarchyResponse",
    "AttributeResponse",
    "AttributeValueResponse",
    "AbbreviationResponse",
    "ClinicalPhraseResponse",
    "ModifierResponse",
    "RelationshipResponse",
    "HealthResponse",
    "ErrorResponse",
    # Phase 4 Responses
    "QuestionResponse",
    "QuestionOptionResponse",
    "AnsweredQuestionResponse",
    "ConceptWithQuestionsResponse",
    "CodeWithQuestionsResponse",
    "SessionResponse",
    "AnswerResponse",
    "GenerateQuestionsResponse",
]
